import { Anthropic } from '@anthropic-ai/sdk';
import OpenAI from 'openai';

export interface StreamingAnalysisConfig {
  text: string;
  provider: 'openai' | 'anthropic' | 'perplexity' | 'deepseek';
  mode: 'normal' | 'comprehensive';
}

export interface StreamingResult {
  analysis: string;
  score: number;
  phase: number;
  completed: boolean;
}

// Core evaluation questions for both Normal and Comprehensive protocols
const CORE_QUESTIONS = `
IS IT INSIGHTFUL? 
DOES IT DEVELOP POINTS? (OR, IF IT IS A SHORT EXCERPT, IS THERE EVIDENCE THAT IT WOULD DEVELOP POINTS IF EXTENDED)? 
IS THE ORGANIZATION MERELY SEQUENTIAL (JUST ONE POINT AFTER ANOTHER, LITTLE OR NO LOGICAL SCAFFOLDING)? OR ARE THE IDEAS ARRANGED, NOT JUST SEQUENTIALLY BUT HIERARCHICALLY? 
IF THE POINTS IT MAKES ARE NOT INSIGHTFUL, DOES IT OPERATE SKILLFULLY WITH CANONS OF LOGIC/REASONING. 
ARE THE POINTS CLICHES? OR ARE THEY "FRESH"? 
DOES IT USE TECHNICAL JARGON TO OBFUSCATE OR TO RENDER MORE PRECISE? 
IS IT ORGANIC? DO POINTS DEVELOP IN AN ORGANIC, NATURAL WAY? DO THEY 'UNFOLD'? OR ARE THEY FORCED AND ARTIFICIAL? 
DOES IT OPEN UP NEW DOMAINS? OR, ON THE CONTRARY, DOES IT SHUT OFF INQUIRY (BY CONDITIONALIZING FURTHER DISCUSSION OF THE MATTERS ON ACCEPTANCE OF ITS INTERNAL AND POSSIBLY VERY FAULTY LOGIC)? 
IS IT ACTUALLY INTELLIGENT OR JUST THE WORK OF SOMEBODY WHO, JUDGING BY THE SUBJECT-MATTER, IS PRESUMED TO BE INTELLIGENT (BUT MAY NOT BE)? 
IS IT REAL OR IS IT PHONY? 
DO THE SENTENCES EXHIBIT COMPLEX AND COHERENT INTERNAL LOGIC? 
IS THE PASSAGE GOVERNED BY A STRONG CONCEPT? OR IS THE ONLY ORGANIZATION DRIVEN PURELY BY EXPOSITORY (AS OPPOSED TO EPISTEMIC) NORMS?
IS THERE SYSTEM-LEVEL CONTROL OVER IDEAS? IN OTHER WORDS, DOES THE AUTHOR SEEM TO RECALL WHAT HE SAID EARLIER AND TO BE IN A POSITION TO INTEGRATE IT INTO POINTS HE HAS MADE SINCE THEN? 
ARE THE POINTS 'REAL'? ARE THEY FRESH? OR IS SOME INSTITUTION OR SOME ACCEPTED VEIN OF PROPAGANDA OR ORTHODOXY JUST USING THE AUTHOR AS A MOUTH PIECE?
IS THE WRITING EVASIVE OR DIRECT? 
ARE THE STATEMENTS AMBIGUOUS? 
DOES THE PROGRESSION OF THE TEXT DEVELOP ACCORDING TO WHO SAID WHAT OR ACCORDING TO WHAT ENTAILS OR CONFIRMS WHAT? 
DOES THE AUTHOR USE OTHER AUTHORS TO DEVELOP HIS IDEAS OR TO CLOAK HIS OWN LACK OF IDEAS?
`;

// Additional questions for detecting impostor scaffolding
const ADDITIONAL_QUESTIONS = `
ARE THERE TERMS THAT ARE UNDEFINED BUT SHOULD BE DEFINED, IN THE SENSE THAT, WITHOUT DEFINITIONS, IT IS DIFFICULT OR IMPOSSIBLE TO KNOW WHAT IS BEING SAID OR THEREFORE TO EVALUATE WHAT IS BEING SAID? IF UNDEFINED TERMS HAVE CLEAR MEANINGS (AS THEY DO IN CHEMISTRY OR PHYSICS), THEN IT MAY WELL BE THAT THEY DO NOT HAVE TO BE DEFINED; BUT IF THEY HAVE NO CANONICAL MEANINGS (E.G. IF THEY ARE IN THE SAME CATEGORY AS "TRANSCENDENTAL EMPIRICISM", "THE MYTH OF THE MENTAL", "MINIMAL EMPIRICISM", OR "LINGUISTIC IDEALISM"), AND THEY ARE UNDEFINED, THEN THE 'STATEMENTS' IN QUESTION MUST NOT BE PRESUMED TO HAVE MEANINGS, ALBEIT HIDDEN ONES; RATHER, THEY MUST BE TREATED AS WHAT THEY ARE, PLACEHOLDER PSEUDO-STATEMENTS THAT HAVE NO MEANINGS AND THEREFORE HAVE NO INTELLIGENT MEANINGS.

ARE THERE "FREE VARIABLES" IN THE TEXT? IE ARE THERE QUALIFICATIONS OR POINTS THAT ARE MADE BUT DO NOT CONNECT TO ANYTHING LATER OR EARLIER? 

DO NEW STATEMENTS DEVELOP OUT OF OLD ONES? OR ARE THEY MERELY "ADDED" TO PREVIOUS ONES, WITHOUT IN ANY SENSE BEING GENERATED BY THEM? 

DO NEW STATEMENTS CLARIFY OR DO THEY LEAD TO MORE LACK OF CLARITY? 

IS THE PASSAGE ACTUALLY (PALPABLY) SMART? OR IS IT ONLY "PRESUMPTION-SMART"? IE IS IT "SMART" ONLY IN THE SENSE THAT THERE EXISTS A PRESUMPTION THAT A DUMB PERSON WOULD NOT REFERENCE SUCH DOCTRINES? AND IS IT SMART ONLY IN THE SENSE THAT IF IT IS PRESUMED THAT UNDEFINED (AND, FOR ALL WE KNOW, MEANINGLESS TERMS) ARE MEANINGFUL, THEN (BUT ONLY THEN--AND POSSIBLY NOT EVEN THEN) IT MIGHT BE THAT WHAT THE AUTHOR IS SAYING IS PALPABLY SMART?

IF YOUR JUDGMENT IS THAT IT IS INSIGHTFUL, CAN YOU STATE THAT INSIGHT IN A SINGLE SENTENCE? OR IF IT CONTAINS MULTIPLE INSIGHTS, CAN YOU STATE THOSE INSIGHTS, ONE PER SENTENCE?

IF I WERE TO GIVE A HIGH SCORE TO THIS PASSAGE, WOULD I BE REWARDING IMPOSTOR SCAFFOLDING? IN OTHER WORDS, WOULD I BE REWARDING THAT HAD SOME OF THE VERBAL AND CONVENTIONAL TRAPPINGS OF 'HIGH LEVEL TEXT' BUT LACKED ANY DISCERNIBLE SUBSTANCE?

IF I WERE TO GIVE A HIGH SCORE TO THIS PASSAGE, WOULD I BE REWARDING CONFORMITY TO ACADEMIC/BUREAUCRATIC NORMS? 

IF I WERE TO GIVE A LOW SCORE TO THIS PASSAGE, WOULD I BE PENALIZING ACTUAL INTELLIGENCE OWING TO A LACK OF CONFORMITY TO ACADEMIC/BUREAUCRATIC NORMS?
`;

// Critical instructions and addendums
const CRITICAL_INSTRUCTIONS = `
A SCORE OF N/100 (E.G. 73/100) MEANS THAT (100-N)/100 (E.G. 27/100) OUTPERFORM THE AUTHOR WITH RESPECT TO THE PARAMETER DEFINED BY THE QUESTION. YOU ARE NOT GRADING; YOU ARE ANSWERING THESE QUESTIONS. YOU DO NOT USE A RISK-AVERSE STANDARD; YOU DO NOT ATTEMPT TO BE DIPLOMATIC; YOU DO NOT ATTEMPT TO COMPLY WITH RISK-AVERSE, MEDIUM-RANGE IQ, ACADEMIC NORMS. YOU DO NOT MAKE ASSUMPTIONS ABOUT THE LEVEL OF THE PAPER; IT COULD BE A WORK OF THE HIGHEST EXCELLENCE AND GENIUS, OR IT COULD BE THE WORK OF A MORON.
IF A WORK IS A WORK OF GENIUS, YOU SAY THAT, AND YOU SAY WHY; YOU DO NOT SHY AWAY FROM GIVING WHAT MIGHT CONVENTIONALLY BE REGARDED AS EXCESSIVELY "SUPERLATIVE" SCORES; YOU GIVE IT THE SCORE IT DESERVES, NOT THE SCORE THAT A MIDWIT COMMITTEE WOULD SAY IT DESERVES. 
THINK VERY VERY VERY HARD ABOUT YOUR ANSWERS; DO NOT DEFAULT TO COOKBOOK, MIDWIT EVALUATION PROTOCOLS.

DO NOT GIVE CREDIT MERELY FOR USE OF JARGON OR FOR REFERENCING AUTHORITIES. FOCUS ON SUBSTANCE. ONLY GIVE POINTS FOR SCHOLARLY REFERENCES/JARGON IF THEY UNAMBIGUOUSLY INCREASE SUBSTANCE.
`;

const METAPOINTS = `
METAPOINT 1: THIS IS NOT A GRADING APP. YOU GRADE THE INTELLIGENCE OF WHAT YOU ARE GIVEN. IF YOU ARE GIVEN A BRILLIANT FRAGMENT, YOU GIVE IT A HIGH SCORE. YOU ARE NOT GRADING ESSAYS. YOU ARE NOT LOOKING FOR COMPLETENESS. YOUR JOB IS TO ANSWER THE QUESTIONS, PERIOD, AND TO DO SO ON THE BASIS OF THE TEXT GIVEN, MAKING ZERO ASSUMPTIONS ABOUT WHETHER IT IS COMPLETE OR INCOMPLETE, OR FOR SCHOOL OR FOR SOME OTHER CONTEXT.

METAPOINT 2: DO NOT OVERVALUE TURNS OF PHRASE. AN AUTHOR SPEAKING CONFIDENTLY IS NOT NECESSARILY "SHUTTING DOWN MODES OF INQUIRY". IN FACT, IT IS LIKELY TO BE THE OPPOSITE; BY PUTTING A CLEAR STAKE IN THE GROUND, HE IS PROBABLY OPENING THEM. ANOTHER EXAMPLE: CASUAL SPEECH DOES NOT MEAN DISORGANIZED THOUGHTS. DON'T JUDGE A BOOK BY ITS COVER.

METAPOINT 3: THE APP SHOULD ALWAYS START BY SUMMARIZING THE TEXT AND ALSO CATEGORIZING IT.

METAPOINT 4: THE APP SHOULD NOT CHANGE THE GRADING BASED ON THE CATEGORY OF THE TEXT: IF A TEXT IS CATEGORIZED AS 'ADVANCED SCHOLARSHIP', IT SHOULD STILL EVALUATE IT WITH RESPECT TO THE GENERAL POPULATION, NOT WITH RESPECT ONLY TO 'ADVANCED SCHOLARLY WORKS.'

METAPOINT 5: THIS IS NOT A GRADING APP. DO NOT PENALIZE BOLDNESS. DO NOT TAKE POINTS AWAY FOR INSIGHTS THAT, IF CORRECT, STAND ON THEIR OWN. GET RID OF THE IDEA THAT "ARGUMENTATION" IS WHAT MAKES SOMETHING SMART; IT ISN'T. WHAT MAKES SOMETHING SMART IS THAT IT IS SMART (INSIGHTFUL). PERIOD.
`;

// The "transcendental empiricism" example that should score ≤65
const NEGATIVE_EXAMPLE = `
In this dissertation, I critically examine the philosophy of transcendental empiricism. Transcendental empiricism is, among other things, a philosophy of mental content. It attempts to dissolve an epistemological dilemma of mental content by splitting the difference between two diametrically opposed accounts of content. John McDowell's minimal empiricism and Richard Gaskin's minimalist empiricism are two versions of transcendental empiricism. Transcendental empiricism itself originates with McDowell's work. This dissertation is divided into five parts. First, in the Introduction, I state the Wittgensteinian metaphilosophical orientation of transcendental empiricism. This metaphilosophical approach provides a plateau upon which much of the rest of this work may be examined. Second, I offer a detailed description of McDowell's minimal empiricism. Third, I critique Gaskin's critique and modification of McDowell's minimal empiricism. I argue that (1) Gaskin's critiques are faulty and that (2) Gaskin's minimalist empiricism is very dubious. Fourth, I scrutinize the alleged credentials of McDowell's minimal empiricism. I argue that McDowell's version of linguistic idealism is problematic. I then comment on a recent dialogue between transcendental empiricism and Hubert Dreyfus's phenomenology. The dialogue culminates with Dreyfus's accusation of the "Myth of the Mental." I argue that this accusation is correct in which case McDowell's direct realism is problematic. I conclude that minimal empiricism does not dissolve the dilemma of mental content. Finally, I argue that Tyler Burge successfully undermines the doctrine of disjunctivism, but disjunctivism is crucial for transcendental empiricism. Ultimately, however, I aim to show that transcendental empiricism is an attractive alternative to philosophies of mental content.
`;

// Positive examples that should score ≥96
const POSITIVE_EXAMPLES = [
  `One cannot have the concept of a red object without having the concept of an extended object. But the word "red" doesn't contain the word "extended." In general, our concepts are interconnected in ways in which the corresponding words are not interconnected. This is not an accidental fact about the English language or about any other language: it is inherent in what a language is that the cognitive abilities corresponding to a person's abilities to use words cannot possibly be reflected in semantic relations holding among those words. This fact in its turn is a consequence of the fact that expressions are, whereas concepts are not, digital structures, for which reason the ways in which cognitive abilities interact cannot possibly bear any significant resemblance to the ways in which expressions interact. Consequently, there is no truth to the contention that our thought-processes are identical with, or bear any resemblance to, the digital computations that mediate computer-activity.`,
  
  `Sense-perceptions do not have to be deciphered if their contents are to be uploaded, the reason being that they are presentations, not representations. Linguistic expressions do have to be deciphered if their contents are to be uploaded, the reason being that they are representations, not presentations. It is viciously regressive to suppose that information-bearing mental entities are categorically in the nature of representations, as opposed to presentations, and it is therefore incoherent to suppose that thought is mediated by expressions or, therefore, by linguistic entities. Attempts to neutralize this criticism inevitably overextend the concept of what it is to be a linguistic symbol, the result being that such attempts eviscerate the very position that it is their purpose to defend. Also, it is inherent in the nature of such attempts that they assume the truth of the view that for a given mental entity to bear this as opposed to that information is for that entity to have this as opposed to that causal role. This view is demonstrably false, dooming to failure the just-mentioned attempts to defend the contention that thought is in all cases mediated by linguistic symbols.`,
  
  `It is shown (i) that causation exists, since we couldn't even ask whether causation existed unless it did; (ii) that any given case of causation is a case of persistence; and (iii) that spatiotemporal relations supervene on causal relations. (ii) is subject to the qualification that we tend not to become aware of instances of causation as such except when two different causal lines---i.e. two different cases of persistence---intersect, resulting in a breakdown of some other case of persistence, this being why we tend to regard instances of causation as fundamentally disruptive, as opposed to preservative in nature. The meaning of (iii) is that spatiotemporal relations are causal relations considered in abstraction of the various specific differences holding between different kinds of causation.`
];

// Sniper Amendment for Phase 1
const SNIPER_AMENDMENT = `
Before answering the questions, note the following non-negotiable standard:

Insight is a sniper shot, not a town hall. If the text reveals something true but unpopular, penalizing it for lacking 'balance' or 'rigor' is midwit bias. Truth often looks extreme because lies are normalized.

Hierarchy of judgment:
95-100/100: Unignorable insight. Either genius or so correct it breaks scales.
80-94/100: Strong but with friction (e.g., clumsy expression, minor gaps).
<80/100: Degrees of mediocrity or failure.

Walmart metric is a sanity check, not a gag. If you claim 30/100 Walmart patrons outperform the author, you must describe exactly what those 30% know that the author doesn't. No vague handwaving.
`;

export class StreamingProtocolService {
  private openai: OpenAI;
  private anthropic: Anthropic;

  constructor() {
    this.openai = new OpenAI({
      apiKey: process.env.OPENAI_API_KEY,
    });
    this.anthropic = new Anthropic({
      apiKey: process.env.ANTHROPIC_API_KEY,
    });
  }

  async *streamNormalProtocol(config: StreamingAnalysisConfig): AsyncGenerator<{ chunk: string; completed: boolean; score?: number }> {
    const prompt = this.buildPhase1Prompt(config.text);
    yield* this.streamWithProvider(config.provider, prompt);
  }

  async *streamComprehensiveProtocol(config: StreamingAnalysisConfig): AsyncGenerator<{ chunk: string; phase: number; completed: boolean; score?: number }> {
    let currentScore = 0;
    
    // Phase 1
    const phase1Prompt = this.buildPhase1Prompt(config.text);
    let phase1Response = '';
    
    for await (const chunk of this.streamWithProvider(config.provider, phase1Prompt)) {
      yield { chunk: chunk.chunk, phase: 1, completed: false };
      phase1Response += chunk.chunk;
      if (chunk.completed && chunk.score) {
        currentScore = chunk.score;
      }
    }

    // Phase 2: Pushback if score < 95
    if (currentScore < 95) {
      const phase2Prompt = this.buildPhase2Prompt(config.text, currentScore, phase1Response);
      let phase2Response = '';
      
      yield { chunk: '\n\n--- PHASE 2: PUSHBACK ---\n\n', phase: 2, completed: false };
      
      for await (const chunk of this.streamWithProvider(config.provider, phase2Prompt)) {
        yield { chunk: chunk.chunk, phase: 2, completed: false };
        phase2Response += chunk.chunk;
        if (chunk.completed && chunk.score) {
          currentScore = chunk.score;
        }
      }
    }

    // Phase 3: Walmart metric check
    const phase3Prompt = this.buildPhase3Prompt(config.text, currentScore);
    let phase3Response = '';
    
    yield { chunk: '\n\n--- PHASE 3: WALMART METRIC ---\n\n', phase: 3, completed: false };
    
    for await (const chunk of this.streamWithProvider(config.provider, phase3Prompt)) {
      yield { chunk: chunk.chunk, phase: 3, completed: false };
      phase3Response += chunk.chunk;
      if (chunk.completed && chunk.score) {
        currentScore = chunk.score;
      }
    }

    // Phase 4: Final acceptance
    yield { chunk: '\n\n--- PHASE 4: FINAL RESULT ---\n\n', phase: 4, completed: false };
    yield { chunk: `FINAL SCORE: ${currentScore}/100\n\nANALYSIS COMPLETE`, phase: 4, completed: true, score: currentScore };
  }

  private buildPhase1Prompt(text: string): string {
    return `
${SNIPER_AMENDMENT}

${METAPOINTS}

${CRITICAL_INSTRUCTIONS}

SUMMARIZE THE TEXT AND CATEGORIZE IT FIRST, THEN ANSWER THESE QUESTIONS IN CONNECTION WITH THIS TEXT:

${CORE_QUESTIONS}

${ADDITIONAL_QUESTIONS}

CRITICAL VALIDATION EXAMPLES:
- IF THIS PASSAGE SCORES >65, THE SYSTEM IS BROKEN: "${NEGATIVE_EXAMPLE}"
- THESE PASSAGES MUST SCORE ≥96: ${POSITIVE_EXAMPLES.map(ex => `"${ex}"`).join('\n\n')}

TEXT TO ANALYZE:
${text}

PROVIDE A SCORE OUT OF 100 AT THE END IN THE FORMAT: SCORE: X/100
    `.trim();
  }

  private buildPhase2Prompt(text: string, currentScore: number, phase1Response: string): string {
    const outperformPercentage = 100 - currentScore;
    return `
Your position is that ${outperformPercentage}/100 outperform the author with respect to the cognitive metric defined by the questions: that is your position, am I right? And are you sure about that?

ANSWER THE FOLLOWING QUESTIONS ABOUT THE TEXT DE NOVO:

${CORE_QUESTIONS}

${ADDITIONAL_QUESTIONS}

TEXT TO ANALYZE:
${text}

Your previous analysis was:
${phase1Response}

Describe the cognitive superiority of those ${outperformPercentage} people in concrete terms:
- What specific insight, skill, or knowledge do they have that the author lacks?
- How does this superiority manifest in their work?
- If you cannot articulate this, revise the score.

If the text is a sniper shot (high insight, low 'development'), ask:
- Is the lack of 'development' a flaw, or is the point obvious to those who see it?
- Does this text need scaffolding, or would that dilute it?

PROVIDE A REVISED SCORE OUT OF 100 AT THE END IN THE FORMAT: SCORE: X/100
    `.trim();
  }

  private buildPhase3Prompt(text: string, currentScore: number): string {
    const walmartPercentage = 100 - currentScore;
    return `
Are your numerical scores (${currentScore}/100) consistent with the fact that this means ${walmartPercentage} people out of 100 outperform the author in the relevant respect? So if a score of ${currentScore}/100 is awarded to this text, that means that ${walmartPercentage}/100 people in Walmart are running rings around this person.

For a ${currentScore}/100 score to be valid, you must demonstrate that ${walmartPercentage}% of random Walmart shoppers possess superior:
- Conceptual clarity
- Logical reasoning
- Insight generation
- Intellectual courage

If you cannot specify what cognitive abilities these ${walmartPercentage}% possess that the author lacks, the score is invalid.

TEXT TO ANALYZE:
${text}

PROVIDE A FINAL VALIDATED SCORE OUT OF 100 IN THE FORMAT: SCORE: X/100
    `.trim();
  }

  private async *streamWithProvider(provider: string, prompt: string): AsyncGenerator<{ chunk: string; completed: boolean; score?: number }> {
    try {
      if (provider === 'anthropic') {
        yield* this.streamAnthropic(prompt);
      } else if (provider === 'openai') {
        yield* this.streamOpenAI(prompt);
      } else {
        throw new Error(`Provider ${provider} not implemented for streaming`);
      }
    } catch (error) {
      console.error(`Streaming error with ${provider}:`, error);
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      yield { chunk: `Error: ${errorMessage}`, completed: true };
    }
  }

  private async *streamAnthropic(prompt: string): AsyncGenerator<{ chunk: string; completed: boolean; score?: number }> {
    const stream = await this.anthropic.messages.create({
      model: 'claude-3-5-sonnet-20241022',
      max_tokens: 4000,
      messages: [{ role: 'user', content: prompt }],
      stream: true,
    });

    let fullResponse = '';
    
    for await (const chunk of stream) {
      if (chunk.type === 'content_block_delta' && chunk.delta.type === 'text_delta') {
        const text = chunk.delta.text;
        fullResponse += text;
        yield { chunk: text, completed: false };
      }
    }

    // Extract score from response
    const score = this.extractScore(fullResponse);
    yield { chunk: '', completed: true, score };
  }

  private async *streamOpenAI(prompt: string): AsyncGenerator<{ chunk: string; completed: boolean; score?: number }> {
    const stream = await this.openai.chat.completions.create({
      model: 'gpt-4',
      messages: [{ role: 'user', content: prompt }],
      stream: true,
      max_tokens: 4000,
    });

    let fullResponse = '';

    for await (const chunk of stream) {
      const content = chunk.choices[0]?.delta?.content || '';
      if (content) {
        fullResponse += content;
        yield { chunk: content, completed: false };
      }
    }

    // Extract score from response
    const score = this.extractScore(fullResponse);
    yield { chunk: '', completed: true, score };
  }

  private extractScore(response: string): number {
    // Look for patterns like "SCORE: 75/100", "75/100", "Score: 75"
    const scorePatterns = [
      /SCORE:\s*(\d+)\/100/i,
      /(\d+)\/100/,
      /Score:\s*(\d+)/i,
      /Final score:\s*(\d+)/i
    ];

    for (const pattern of scorePatterns) {
      const match = response.match(pattern);
      if (match) {
        const score = parseInt(match[1], 10);
        if (score >= 0 && score <= 100) {
          return score;
        }
      }
    }

    // Default to 50 if no score found
    console.warn('No valid score found in response, defaulting to 50');
    return 50;
  }
}